# Generated by Django 4.2.15 on 2026-05-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="virtualcards",
            options={
                "verbose_name": "Virtual Card",
                "verbose_name_plural": "Virtual Cards",
            },
        ),
    ]
