# Generated by Django 4.2.15 on 2026-05-07 03:05

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_alter_nextofkin_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("us_dollar", "US Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("naira", "Naira"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("current", "Current Account"),
                    ("savings", "Savings Account"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Type",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id_expiry_date",
            field=models.DateField(
                default=datetime.date(2026, 1, 1),
                verbose_name="ID or Passport Expiry Date",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id_issued_date",
            field=models.DateField(
                default=datetime.date(2000, 1, 1),
                verbose_name="ID or Passport Issued Date",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id_number",
            field=models.CharField(
                default=datetime.date(2026, 1, 1),
                max_length=50,
                verbose_name="ID or Passport Number",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+250784123456",
                max_length=30,
                region="NG",
                verbose_name="Phone Number",
            ),
        ),
    ]
