# Generated by Django 4.2.15 on 2026-05-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_alter_profile_account_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("us_dollar", "US Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("naira", "Naira"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
    ]
