# Generated by Django 4.2.15 on 2026-05-07 04:00

import core_apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="currency",
            field=models.CharField(
                choices=[
                    ("us_dollar", "US Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("naira", "Naira"),
                ],
                default=core_apps.accounts.models.BankAccount.AccountCurrency,
                max_length=20,
                verbose_name="Currency",
            ),
        ),
    ]
