# Generated by Django 4.2.15 on 2026-05-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_bankaccount_verification_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Annual interest rate as a decimal (e.g 0.0150 for 1.50%)",
                max_digits=5,
                verbose_name="Interest Rate",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("transfer", "Transfer"),
                    ("interest", "Interest"),
                ],
                max_length=20,
                verbose_name="Transaction Type",
            ),
        ),
    ]
