# Generated by Django 4.2.15 on 2026-04-21 16:31

import core_apps.user_auth.managers
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Username"
                    ),
                ),
                (
                    "security_question",
                    models.CharField(
                        choices=[
                            (
                                "('maiden_name', \"What is your mother's maiden name?\")",
                                "Maiden Name",
                            ),
                            (
                                "('birth_city', 'What city were you born?')",
                                "Birth City",
                            ),
                            (
                                "('best_friend_name', \"What is your childhood friend's name?\")",
                                "Childhood Friend",
                            ),
                            ("favourite_colour", "What is your favourite colour?"),
                        ],
                        max_length=100,
                        verbose_name="Security Question",
                    ),
                ),
                (
                    "security_answer",
                    models.CharField(
                        max_length=50, verbose_name="Security Question Answer"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=100, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="First Name"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Last Name"
                    ),
                ),
                (
                    "id_no",
                    models.PositiveBigIntegerField(unique=True, verbose_name="ID No"),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("('active', 'Active')", "Active"),
                            ("('locked', 'Locked')", "Locked"),
                        ],
                        max_length=50,
                        verbose_name="Account Status",
                    ),
                ),
                (
                    "roles",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("account_executive", "Account Executive"),
                            ("('teller', 'Teller')", "Teller"),
                            ("branch_manager", "Branch Manager"),
                        ],
                        max_length=50,
                        verbose_name="User Role",
                    ),
                ),
                ("failed_login_attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_failed_login", models.DateTimeField(blank=True, null=True)),
                ("otp", models.CharField(blank=True, max_length=6, verbose_name="OTP")),
                (
                    "otp_expiry_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="OTP Expiry Time"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", core_apps.user_auth.managers.UserManager()),
            ],
        ),
    ]
