# Generated by Django 4.2.15 on 2026-05-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[("active", "Active"), ("locked", "Locked")],
                max_length=50,
                verbose_name="Account Status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("account_executive", "Account Executive"),
                    ("teller", "Teller"),
                    ("branch_manager", "Branch Manager"),
                ],
                max_length=50,
                verbose_name="User Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="security_question",
            field=models.CharField(
                choices=[
                    ("maiden_name", "What is your mother's maiden name?"),
                    ("birth_city", "What city were you born?"),
                    ("best_friend_name", "What is your childhood friend's name?"),
                    ("favourite_colour", "What is your favourite colour?"),
                ],
                max_length=100,
                verbose_name="Security Question",
            ),
        ),
    ]
