# add an upstream directive => allows you to define multiple servers which nginx can distribute the load among servers
# based on the specified method, and by default it's the "Round Robin".

upstream api {
    server api:8000;
}

# declare the log format
# $remote_addr - client ip address
# time_local - local time when the rquest was received
# body_bytes_sent - number of bytes sent excluding the headers
# http_referer - referer header from client request
# http_user_agent - user ahent header from the client
# request_time - total time spent to processing the request
# upstream_response_time - time the upstream server to respond
# http_forwarded_for - use to pass client original ip address through proxy
log_format detailed_log '$remote_addr - $upstream_http_x_django_user - [$time_local]'
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent" '
                        '$request_time upstream_response_time '
                        '"$http_x_forwarded_for" ';

# Declare the server block -  contains the main config for the nginx server and acts as our reverse proxy
# client_max_body_size - Max client's request body
# proxy_set_header - allows you to modify the proxy header sent to the proxy server
# X-Forwarded-Proto - to set the client request protocol whether it's http or https
# proxy_pass_header - ensure nginx is going to pass X-Django-User to the request header from our upstream server
# location - tells nginx to redirect the requests to the different endpoints
# proxy_pass - tells nginx to pass the request to our api upstream server
# to serve a static file, you add an alias directive that'll tell the nginx server to serve the static files from the specified # directory
# expires 30d - means nginx should cached the staticfiles for 30 days
# public -  the response can be cached by any intermediate server
# Cache-Control - tells how long to cach the staticfiles
server {
    listen 80;

    client_max_body_size 20M;

    error_log /var/log/nginx/error.log error;

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass_header X-Django-User;

    location /api/v1/ {
        proxy_pass http://api;
        access_log /var/log/api_access.log detailed_log;
        error_log /var/log/api_error.log error;
    }

    location /admin-supersecret {
        proxy_pass http://api;
        access_log /var/log/nginx/admin_access.log detailed_log;
    }

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;

        add_header Cache-Control "public, max-age=2592000";
    }

}
